PIntegrador/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('presentacion.urls')),
]

presentacion/urls.py
from django.urls import path
from . import views

# Nombre de la aplicación
app_name = 'Presentacion'

# Definición de las URLs
urlpatterns = [
    path('', views.Inicio, name='inicio'),  
    # Ruta para la página de inicio
    path('sobrenosotros', views.SobreN, name='sobre'),  
    # Ruta para la página "Sobre Nosotros"
    path('contacto', views.Contacto, name='contacto'),  
    # Ruta para la página de contacto
    path('autenticar', views.Autenticar, name='autenticar'),  
    # Ruta para la autenticación de usuarios
    path('verdatos', views.VerdatosUBD, name='datos'),  
    # Ruta para ver los datos de usuarios registrados
    path('consultasavanzadas', views.Consultas, name='consultas'),  
    # Ruta para la página de consultas avanzadas
    path('iniciarsession', views.IniciarSession, name='Isession'),  
    # Ruta para iniciar sesión
    path('registro', views.RegistroU, name='Rusuario'),  
    # Ruta para la página de registro de usuarios
    path('val2', views.RegistrarUBD, name='registrarUBD'),  
    # Ruta para registrar un nuevo usuario en la base de datos
    path('val3', views.EliminarUBD, name='eliminarUBD'),  
    # Ruta para eliminar un usuario de la base de datos
    path('val4', views.Iractualizar, name='iractualizar'),  
    # Ruta para ir a la página de actualización de datos de usuario
    path('val5', views.ActulizarUBD, name='actualizarUBD'),  
    # Ruta para actualizar datos de usuario en la base de datos
    path('consulta1', views.ConsultaTime, name='consultaTiempo'),  
    # Ruta para la consulta de tiempo de un usuario
    path('consulta2', views.ConsultaCant, name='consultaCantidad'),  
    # Ruta para la consulta de cantidad de productos por usuario
    path('consulta3', views.ConsultaHora, name='consultaHoras'),  
    # Ruta para la consulta de horas trabajadas por usuario
    path('consulta4', views.ConsultaBuscar, name='consultaBuscar'),  
    # Ruta para la consulta específica de búsqueda de usuarios
    path('consulta5', views.ConsultaUPRegistrados, name='ConsultaUPR'),  
    # Ruta para la consulta de usuarios con productos registrados
]

presentacion/models.py
from django.db import models

# Create your models here.

presentacion/views.py
from django.shortcuts import render
from django.http import HttpResponse
from firebase_config import FirebaseDB
from firebase_admin import db

# Rutas y URL de Firebase
path = "d:/Instituto-4Ciclo/PROYECTO INTEGRADOR/Aplicaciones Empresariales/Prototipo2-pagina/administrador/Interfaz/project_credentials.json"
url = "https://respaldor-84fa0-default-rtdb.firebaseio.com/"
fb_db = FirebaseDB(path, url)

# Vista para la página de inicio
def Inicio(request):
    return render(request, 'Inicio.html')

# Vista para la página "Sobre Nosotros"
def SobreN(request):
    return render(request, 'SobreN.html')

# Vista para la página de contacto
def Contacto(request):
    return render(request, 'Contacto.html')

# Vista para la página de inicio de sesión
def IniciarSession(request):
    return render(request, 'Isession.html') 

# Vista para la página de consultas
def Consultas(request):
    return render(request, 'ConsultasA.html')

# Vista para la página de registro de usuarios
def RegistroU(request):
    return render(request, 'RegistrarU.html')

# Función para autenticar usuarios
def Autenticar(request):
    if request.method == 'POST':
        usuario = request.POST.get('username')
        contraseña = request.POST.get('contraseña')

        data = fb_db.read_record("usuarios")

        # Iterar sobre los usuarios y verificar las credenciales
        for users, usuarios in data.items():
            if usuarios['usuarioRef'] == usuario and usuarios['contraseña'] == contraseña:
                # Iniciar sesión y redirigir al usuario a la página de inicio si las credenciales son válidas
                return Inicio(request)
        
        # Devolver un mensaje de error si las credenciales son incorrectas
        return HttpResponse("Error al iniciar sesión. Credenciales incorrectas.")

# Función para registrar usuarios en la base de datos
def RegistrarUBD(request):
    if request.method == 'POST':
        correo = request.POST.get('correo1')
        usuario = request.POST.get('usuario1')
        contraseña1 = request.POST.get('contraseña1')
        contraseña2 = request.POST.get('contraseña2')

        # Verificar que las contraseñas coincidan
        if contraseña1 != contraseña2:
            return HttpResponse("Las contraseñas no son iguales.")
        
        usuarios_ref = db.reference('/users')
        datos_usuarios = usuarios_ref.get()

        # Verificar si el usuario ya existe en la base de datos
        if datos_usuarios:
            for info_usuario in datos_usuarios.values():
                if info_usuario.get('usuario') == usuario:
                    return HttpResponse("El usuario ya existe. Intente con otro nombre de usuario.")
         
        data = {
            'email': correo,
            'usuarioRef': usuario,
            'contraseña': contraseña1   
        }

        try:
            # Guardar el registro del usuario en la base de datos Firebase
            fb_db.write_record(f'/usuarios/{usuario}', data)
            return render(request,'Isession.html')
        except Exception as e:
            return HttpResponse(f"Error al guardar en la base de datos: {str(e)}")

    return render(request, 'Inicio.html')

# Función para ver los datos de usuarios almacenados en la base de datos
def VerdatosUBD(request):
    data = fb_db.read_record("usuarios")
    
    # Convertir el diccionario de datos en una lista de tuplas para la plantilla
    results = [(key, value['email'], value['contraseña']) for key, value in data.items()]
    
    return render(request, 'Verdatos.html', {'results': results})

# Función para eliminar usuarios de la base de datos
def EliminarUBD(request):
    if request.method == 'POST':
        usuario_id = request.POST.get('usuario_id')
        
        # Eliminar el registro del usuario de la base de datos
        fb_db.delete_record(f'/usuarios/{usuario_id}')

        return VerdatosUBD(request)

# Función para preparar la actualización de datos de usuario
def Iractualizar(request):
    if request.method == 'POST':
        usuario_id = request.POST.get('usuario_id')
        data = fb_db.read_record(f'/usuarios/{usuario_id}')
        
        # Obtener los datos del usuario si existen
        if isinstance(data, dict):
            email = data.get('email', '')
            contrasena = data.get('contraseña', '')
        else:
            email, contrasena = '', '', ''
        
        context = {
            'usuario_id': usuario_id,
            'email': email,
            'contrasena': contrasena,
        }
        
        return render(request, 'Actualizar.html', context)

# Función para actualizar los datos de usuario en la base de datos
def ActulizarUBD(request):
    if request.method == 'POST':
        correo = request.POST.get('correo1')
        usuario = request.POST.get('usuario_id')
        contraseña1 = request.POST.get('contraseña1')
        contraseña2 = request.POST.get('contraseña2')

        # Verificar que las contraseñas coincidan
        if contraseña1 != contraseña2:
            return HttpResponse("Las contraseñas no son iguales.")
         
        data = {
            'email': correo,
            'contraseña': contraseña1   
        }

        try:
            # Actualizar los datos del usuario en la base de datos Firebase
            fb_db.update_record(f'/usuarios/{usuario}', data)
            return VerdatosUBD(request)
        except Exception as e:
            return HttpResponse(f"Error al guardar en la base de datos: {str(e)}")
        
# Función para consultar el tiempo total de un usuario
def ConsultaTime(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')

        # Obtener los datos del usuario desde Firebase
        data = fb_db.read_record(f"/Time/{usuario}")

        # Inicializar la suma total del tiempo
        tiempo_total = 0

        # Iterar sobre los registros y sumar los valores de "tiempo"
        for fecha, registro in data.items():
            tiempo_total += registro.get('tiempo', 0)

        data = {
            'tiempototal': tiempo_total
        }

        # Devolver el resultado como una respuesta HTTP
        return render(request, 'Consulta1.html', data)

# Función para consultar la cantidad de productos de un usuario
def ConsultaCant(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')

        # Obtener los datos de productos desde Firebase
        data = fb_db.read_record("/productos")

        # Inicializar la cantidad total de productos
        cantidad_total = 0

        # Iterar sobre los registros de productos y contar los que pertenecen al usuario
        for producto_id, producto_data in data.items():
            if producto_data.get('id_usuario') == usuario:
                cantidad_total += 1
        
        # Preparar los datos para la plantilla
        context = {
            'cantidad_total': cantidad_total,
            'usuario': usuario
        }

        # Devolver el resultado como una respuesta HTTP
        return render(request, 'Consulta2.html', context)

# Función para consultar el tiempo total de cada usuario y mostrar los 3 principales
def ConsultaHora(request):
    if request.method == 'POST':
        # Obtener los datos de tiempo desde Firebase
        data = fb_db.read_record("/Time")

        # Diccionario para almacenar el tiempo total de cada usuario
        usuarios_tiempos = {}

        # Iterar sobre los registros de usuarios
        for usuario, fechas in data.items():
            # Inicializar el tiempo total para el usuario
            tiempo_total = 0
            # Sumar los tiempos para cada fecha
            for fecha, registro in fechas.items():
                tiempo_total += registro.get('tiempo', 0)
            # Almacenar el tiempo total en el diccionario
            usuarios_tiempos[usuario] = tiempo_total

        # Ordenar los usuarios por tiempo total de mayor a menor
        usuarios_ordenados = sorted(usuarios_tiempos.items(), key=lambda x: x[1], reverse=True)

        # Seleccionar los tres primeros usuarios
        top_3_usuarios = usuarios_ordenados[:3]

        # Preparar los datos para la plantilla
        context = {
            'top_3_usuarios': top_3_usuarios
        }

        # Renderizar la respuesta
        return render(request, 'Consulta3.html', context)

# Función para buscar usuarios por los primeros 3 caracteres de su usuarioRef
def ConsultaBuscar(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario').lower()  # Convertir a minúsculas

        # Obtener los datos de usuarios desde Firebase
        data = fb_db.read_record("/usuarios")

        encontrados = {}

        # Función para comparar los primeros 3 caracteres
        def compara_hasta_tres_caracteres(cadena1, cadena2):
            # Limitar la comparación a los primeros 3 caracteres
            for c1, c2 in zip(cadena1[:3], cadena2[:3]):
                if c1.lower() != c2.lower():
                    return False
            return True

        # Iterar sobre los usuarios y comparar los primeros 3 caracteres de usuarioRef (en minúsculas)
        for user_id, user_data in data.items():
            if 'usuarioRef' in user_data and compara_hasta_tres_caracteres(usuario, user_data['usuarioRef']):
                encontrados[user_id] = user_data

        context = {
            'encontrados': encontrados
        }

        return render(request, 'Consulta4.html', context)

# Función para consultar usuarios que tengan productos registrados
def ConsultaUPRegistrados(request):
    if request.method == 'POST':
        # Obtener los datos de productos y usuarios desde Firebase
        productos_data = fb_db.read_record("/productos")
        usuarios_data = fb_db.read_record("/usuarios")

        usuarios_con_productos = set()

        # Iterar sobre los productos y agregar usuarios con productos a un set
        for producto_id, producto_data in productos_data.items():

presentacion/templates/Actualizar.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link href="{%static 'DiseñoTemplates/estiloA.css'%}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<h3>u</h3>

<form class="actualizar" action="{% url 'Presentacion:actualizarUBD' %}" method="post">
    {% csrf_token %}
    <h1 class="title">Actualizar Registro</h1>
    <input type="hidden" name="usuario_id" value="{{ usuario_id }}">
    <label>
        <p>USUARIO: {{usuario_id}}</p>
    </label>
    <label>
        <i class="fa-solid fa-envelope"></i>
        <input placeholder="Ingrese Correo" type="email" name="correo1" value="{{ email }}" required>
    </label>

    <label>
        <i class="fa-solid fa-lock"></i>
        <input placeholder="Ingrese la contraseña" type="password" name="contraseña1" value="{{ contrasena }}" required>
    </label>
    <label>
        <i class="fa-solid fa-lock"></i>
        <input placeholder="Confirme la contraseña" type="password" name="contraseña2" value="{{ contrasena }}"
            required>
    </label>
    <button type="submit" id="button">Actualizar</button>
</form>

{% endblock %}

presentacion/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Aurora</title>
	<link href="{% static 'DiseñoTemplates/estiloB.css' %}" rel="stylesheet"> <!-- Enlace al archivo CSS de estilos -->
	<link rel="icon" type="image/jpg" href="{% static 'img/moon.png' %}"> <!-- Icono de la pestaña del navegador -->
</head>

<body>
	<header>
		<div class="container-hero">
			<div class="container hero">
				<!-- Sección de soporte al cliente -->
				<div class="customer-support">
					<i class="fa-solid fa-headset" style="color: rgba(150, 143, 143, 0.822);"></i>
					<div class="content-customer-support">
						<span class="text" style="color: #ffffff;">Soporte al cliente</span>
						<a href="https://wa.link/2dsfgq" style="text-decoration: none;"><span
								class="number" style="color: #626B92;">976739455</span></a>
					</div>
				</div>

				<!-- Logo y nombre del sitio -->
				<div class="container-logo">
					<i class="fa-solid fa-moon" style="color: rgba(150, 143, 143, 0.822);"></i>
					<h1 class="logo"><a href="/" style="color: #ffffff;">Aurora</a></h1>
				</div>

				<!-- Enlace al inicio de sesión -->
				<div class="container-user">
					<a href="{% url 'Presentacion:Isession' %}"><i class="fa-solid fa-user" style="color: rgba(150, 143, 143, 0.822);"></i></a>
				</div>
			</div>
		</div>

		<!-- Barra de navegación -->
		<div class="container-navbar">
			<nav class="navbar container">
				<i class="fa-solid fa-bars" style="color: rgba(34, 3, 3, 0.822);"></i>
				<ul class="menu">
					<!-- Opciones del menú -->
					<li><a href="{% url 'Presentacion:inicio' %}">Inicio</a></li>
					<li><a href="{% url 'Presentacion:sobre' %}">Sobre Nosotros</a></li>
					<li><a href="{% url 'Presentacion:contacto' %}">Contacto</a></li>
					<li><a href="{% url 'Presentacion:datos' %}">Datos</a></li>
					<li><a href="{% url 'Presentacion:consultas' %}">Más</a></li>
				</ul>

				<!-- Formulario de búsqueda -->
				<form class="search-form">
					<input type="search" placeholder="Buscar..." />
					<button class="btn-search">
						<i class="fa-solid fa-magnifying-glass"></i>
					</button>
				</form>
			</nav>
		</div>
	</header>

	<!-- Apartado para colocar bloques de codigo en otras plantillas -->
	<div>
		<section>
			<div>
				{% block content %}
				{% endblock %}
			</div>
		</section>
	</div>

	<script src="https://kit.fontawesome.com/81581fb069.js" crossorigin="anonymous"></script> <!-- Script para FontAwesome -->
</body>

</html>

presentacion/templates/Consulta1.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{%static 'DiseñoTemplates/estiloC1.css'  %}">
<div class="resultado">
    <h1>Resultado de la Consulta</h1>
    <p>El tiempo total calculado es:</p>
    <label id="milabel">{{ tiempototal }}</label>
    <p>Gracias por utilizar nuestro servicio.</p>
    <button class="btn-atras" onclick="window.history.back()">Atrás</button>
</div> 

{% endblock %}

presentacion/templates/Consulta2.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{%static 'DiseñoTemplates/estiloC2.css'  %}">

<div class="resultado">
    <h1>Resultado de la Consulta</h1>
    <p>Cantidad de Productos para el Usuario {{ usuario }}</p>
    <label id="milabel">{{ cantidad_total }}</label>
    <p>Gracias por utilizar nuestro servicio.</p>
    <button class="btn-atras" onclick="window.history.back()">Atrás</button>
</div> 
{% endblock %}

presentacion/templates/Consulta3.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{%static 'DiseñoTemplates/estiloC3.css'  %}">

<div class="resultado">
    <h1>Resultado de la Consulta</h1>
    <p>Top 3 Usuarios con Mayor Tiempo</p>
    <label id="milabel">
        <ul class="sin-vineta">
            {% for usuario, tiempo in top_3_usuarios %}
            <li>Usuario: {{ usuario }}, Tiempo: {{ tiempo }}</li>
            {% endfor %}
        </ul>
    </label>
    <p>Gracias por utilizar nuestro servicio.</p>
    <button class="btn-atras" onclick="window.history.back()">Atrás</button>
</div>
{% endblock %}

presentacion/templates/Consulta4.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{%static 'DiseñoTemplates/estiloC4.css'  %}">

<div class="resultado">
    <h1>Resultado de la Consulta</h1>
    <p>Usuarios Encontrados</p>
    <label id="milabel">
        <ul class="sin-vineta">
            {% for user_id, user_data in encontrados.items %}
            <li>Usuario ID: {{ user_id }}</li>
            <li>Email: {{ user_data.email }}</li>
            <li>Contraseña: {{ user_data.contraseña }}</li>
            {% endfor %}
        </ul>
    </label>
    <p>Gracias por utilizar nuestro servicio.</p>
    <button class="btn-atras" onclick="window.history.back()">Atrás</button>
</div>
{% endblock %}

presentacion/templates/Consulta5.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{%static 'DiseñoTemplates/estiloC5.css'  %}">

<div class="resultado">
    <h1>Resultado de la Consulta</h1>
    <p>Usuarios con Productos Registrados</p>
    <label id="milabel">
        <ul class="sin-vineta">
            {% for user_id, user_data in encontrados.items %}
            <li>Usuario ID: {{ user_id }}</li>
            {% endfor %}
        </ul>
    </label>
    <p>Gracias por utilizar nuestro servicio.</p>
    <button class="btn-atras" onclick="window.history.back()">Atrás</button>
</div>
{% endblock %}

presentacion/templates/ConsultasA.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{%static 'DiseñoTemplates/estiloCA.css'  %}">

<nav class="vertical-nav">
    <ul>
        <li><a href="#" onclick="mostrarFuncionalidad('consulta1')">Tiempo Acumulado por usuario</a></li>
        <li><a href="##" onclick="mostrarFuncionalidad('consulta2')">Cantidad de prodcutos por usuario</a></li>
        <li><a href="###" onclick="mostrarFuncionalidad('consulta3')">Top 3 usuarios con más tiempo</a></li>
        <li><a href="####" onclick="mostrarFuncionalidad('consulta4')">Buscar usuarios</a></li>
        <li><a href="#####" onclick="mostrarFuncionalidad('consulta5')">Usuarios con productos registrados</a></li>
    </ul>
</nav>

<div class="consultas">
    <div id="consulta1" class="funcionalidad">
        <form method="post" action="{% url 'Presentacion:consultaTiempo'%}">
            {% csrf_token %}
            <div class="form-group">
                <label>Ingrese el nombre del usuario</label>
                <input type="text" name="usuario" placeholder="Ingrese Usuario">
            </div>
            <button type="submit">Consultar</button>
        </form>
    </div>

    <div id="consulta2" class="funcionalidad">
        <form method="post" action="{% url 'Presentacion:consultaCantidad'%}">
            {% csrf_token %}
            <div class="form-group">
                <label>Ingrese el nombre del usuario</label>
                <input type="text" name="usuario" placeholder="Ingrese Usuario">
            </div>
            <button type="submit">Consultar</button>
        </form>
    </div>


    <div id="consulta3" class="funcionalidad">
        <form method="post" action="{% url 'Presentacion:consultaHoras'%}">
            {% csrf_token %}
            <label>Personas con más horas</label>
            <button type="submit">Consultar</button>
        </form>
    </div>

    <div id="consulta4" class="funcionalidad">
        <form method="post" action="{% url 'Presentacion:consultaBuscar'%}">
            {% csrf_token %}
            <div class="form-group">
                <label>Buscar Usuarios ingrese min 3 caracteres</label>
                <input type="text" name="usuario" placeholder="Ingrese Usuario">
            </div>
            <button type="submit">Buscar</button>
        </form>
    </div>

    <div id="consulta5" class="funcionalidad">
        <form method="post" action="{% url 'Presentacion:ConsultaUPR'%}">
            {% csrf_token %}
            <label>Usuarios con productos registrados</label>
            <button type="submit">Consultar</button>
        </form>
    </div>

</div>


<script>
    function mostrarFuncionalidad(id) {
        var funcionalidades = document.getElementsByClassName('funcionalidad');
        for (var i = 0; i < funcionalidades.length; i++) {
            if (funcionalidades[i].id !== id) {
                funcionalidades[i].style.display = 'none'; // Ocultar otros elementos
            }
        }
        var funcionalidad = document.getElementById(id);
        funcionalidad.style.display = 'block'; // Mostrar el elemento objetivo
    }
</script>

{% endblock %}

presentacion/templates/Isession.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link href="{%static 'DiseñoTemplates/estiloIS.css'  %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<form class="sesion" action="{% url 'Presentacion:autenticar' %}" method="post">
    {% csrf_token %}
    <h1 class="title">Iniciar Sessión</h1>
    <label>
        <i class="fa-solid fa-user"></i>
        <input placeholder="username" type="text" name="username">
    </label>
    <label>
        <i class="fa-solid fa-lock"></i>
        <input placeholder="password" type="password" name="contraseña">
    </label>
    <a href="{% url 'Presentacion:Rusuario' %}" class="link" style="color: #626B91;">Crear una nueva cuenta</a>

    <button class="bton" type="submit" id="button">Iniciar</button>
</form>


{% endblock %}

presentacion/templates/RegistrarU.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link href="{%static 'DiseñoTemplates/estiloR.css'  %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<form class="sesion" action="{% url 'Presentacion:registrarUBD' %}" method="post">
    {% csrf_token %}
    <h1 class="title">Registro Usuario</h1>
    <label>
        <i class="fa-solid fa-envelope"></i>
        <input placeholder="Ingrese Correo" type="email" name="correo1" required>
    </label>
    <label>
        <i class="fa-solid fa-user"></i>
        <input placeholder="Ingrese Usuario" type="text" name="usuario1" required>
    </label>
    <label>
        <i class="fa-solid fa-lock"></i>
        <input placeholder="Confirme la contraseña" type="password" name="contraseña1" required>
    </label>
    <label>
        <i class="fa-solid fa-lock"></i>
        <input placeholder="Ingrese la contraseña" type="password" name="contraseña2" required>
    </label>
    <a style="color: #626B91;" href="https://wa.link/2dsfgq" class="link">¿Olvidaste tu cuenta?</a>

    <button type="submit" id="button" class="bton">Registrar</button>
</form>

{% endblock %}

presentacion/templates/Verdatos.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<link href="{% static 'DiseñoTemplates/estiloVD.css'  %}" rel="stylesheet">

<div class="ContenedorP">
    <h1 class="titulo">Clientes Premium</h1>
    <h2>{{ mensaje }}</h2>
    <table class="tabla-clientes">
        <thead>
            <tr class="encabezado">
                <th>Usuario</th>
                <th>Correo</th>
                <th>Contraseña</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for data in results %}
            <tr>
                <td>{{ data.0 }}</td>
                <td>{{ data.1 }}</td>
                <td>{{ data.2 }}</td>
                <td>
                    <form method="post" action="{% url 'Presentacion:iractualizar' %}">
                        {% csrf_token %}
                        <input type="hidden" name="usuario_id" value="{{ data.0 }}">
                        <button type="submit" class="Actualizar">Actualizar</button>
                    </form>
                    <form method="post" action="{% url 'Presentacion:eliminarUBD' %}">
                        {% csrf_token %}
                        <input type="hidden" name="usuario_id" value="{{ data.0 }}">
                        <button type="submit" class="Borrar">Eliminar</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock %}